version: '2'
services:    
    prelaunchbuilder:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        privileged: true
        environment:
         - VIRTUAL_HOST=prelaunchbuilder.local
        volumes:
         - ./:/var/www/html
        networks:
         - default
         - dev_net
networks:
    dev_net:
        external: true