#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pts_file_download:
  path:     /download/{id}
  defaults: { _controller: PlumTreeSystems\FileBundle\Controller\FileController::downloadAction }

pts_file_remove:
  path:     /remove/{id}
  defaults: { _controller: PlumTreeSystems\FileBundle\Controller\FileController::removeAction }