#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pts_file_download:
  path:     /api/download/{id}
  defaults: { _controller: PlumTreeSystems\FileBundle\Controller\FileController::downloadAction }

pts_file_remove:
  path:     /api/remove/{id}
  defaults: { _controller: PlumTreeSystems\FileBundle\Controller\FileController::removeAction }

ptsToken:
  resource: "@PlumTreeSystemsUserBundle/Resources/config/routes/tokenSecurityRoutes.yml"
  prefix: /api
