export default {
    adminHome: '/api/admin',
    adminEmailTemplate: '/api/admin/emailtemplate',
    adminEndPrelaunch: '/api/admin/endprelaunch',
    adminChangeContent: '/api/admin/changecontent',
    adminAssociates: '/api/admin/associates',
    adminCSV: '/api/admin/csv',
    adminExplorer: '/api/admin/explorer',
    adminUserSearch: '/api/admin/users',
    adminGallery: '/api/admin/jsonGallery',
    adminRemoveFile: '/api/admin/removeFile',
    adminUploadFile: '/api/admin/uploadFile',
    adminUploadGalleryFile: '/api/admin/uploadGalleryFile',
    adminLogs: '/api/admin/get-logs',
};
